In [3]:
import pandas as pd

from mreyemove.analysis.glm.config import GLMConfig
from SleepMReye.sleepmreye.sleep_mrio import SleepMRIO

mrio = SleepMRIO(
    bids_root="/Users/zach/2025_RA/matthias/bids_sleepmreye",
    tr=2.1,
    task="sleep",
    load_signal=False,
    load_eog=False,
    desc_add="clean-with-fd-clamped",
    # desc_add="raw",
    ignore_boundary_trs=0
)

config = GLMConfig.from_yaml("/Users/zach/2025_RA/matthias/eyemove_and_sleep/SleepMReye/sleepmreye/designs/original_sleep_cer.yml")

report_path = mrio.mreyemove_dir / "group" / "func" / "qc_reports" / "run_inclusion"

In [119]:
from pathlib import Path
import pandas as pd 

mreyemove_path = Path("/Users/zach/2025_RA/matthias/bids_sleepmreye/derivatives/mreyemove/group/func/qc_reports/run_inclusion/clean-20260605-11571780653432.json")
mreyemove_cer_path = Path("/Users/zach/2025_RA/matthias/bids_sleepmreye/derivatives/mreyemove/group/func/qc_reports/run_inclusion/clean-20260605-11181780651138.json")
eog_path = Path("/Users/zach/2025_RA/matthias/bids_sleepmreye/derivatives/mreyemove/group/func/qc_reports/run_inclusion/clean-with-fd-clamped-20260515-16121778854379.json")
eog_path_cer = Path("/Users/zach/2025_RA/matthias/bids_sleepmreye/derivatives/mreyemove/group/func/qc_reports/run_inclusion/clean-20260605-10561780649775.json")
# extended_path = Path("/Users/zach/2025_RA/matthias/bids_sleepmreye/derivatives/mreyemove/group/func/qc_reports/run_inclusion/clean-20260605-10561780649818.json")
# extended_path_cer = Path("/Users/zach/2025_RA/matthias/bids_sleepmreye/derivatives/mreyemove/group/func/qc_reports/run_inclusion/clean-20260605-10571780649862.json")



_df = pd.read_json(eog_path, lines=True)
_df["excluded"] = _df["excluded"] == "True"
_df["above_fd"] = _df["above_fd"] == "True"
_df["invalid_stages"] = _df["invalid_stages"] == "True"
_df_orig =  pd.read_json(mreyemove_path, lines=True)
_df

,subject,run,stage,excluded,eog_run_len,desc_add,invalid_stages,above_fd
0,16,1,eeg,True,0.0,clean-with-fd-clamped,False,False
1,16,2,eeg,True,282.0,clean-with-fd-clamped,False,False
2,16,3,eeg,True,0.0,clean-with-fd-clamped,False,False
3,16,4,eeg,True,234.0,clean-with-fd-clamped,False,False
4,16,5,eeg,True,0.0,clean-with-fd-clamped,False,False
...,...,...,...,...,...,...,...,...
189,28,4,global,False,NaN,clean-with-fd-clamped,False,False
190,15,5,global,False,NaN,clean-with-fd-clamped,False,False
191,28,5,global,False,NaN,clean-with-fd-clamped,False,False
192,15,6,global,False,NaN,clean-with-fd-clamped,False,False
193,28,6,global,True,NaN,clean-with-fd-clamped,True,False

In [112]:
df = _df.copy()
df[(df["invalid_stages"])]

    subject  run   stage  excluded  invalid_stages  above_fd desc_add
79       23    2  global      True            True     False    clean
82       23    3  global      True            True     False    clean

In [118]:
from SleepMReye.sleepmreye.sleep_mrio import SleepMRIO

# mrio = SleepMRIO(
#     bids_root="/Users/zach/2025_RA/matthias/bids_sleepmreye",
#     # exclude_subjects=["01", "07", "09", "12"],
#     tr=2.1,
#     task="sleep",
#     load_eog=False,
#     desc_add="clean",
# )

VALID_EVENT_STAGES = ["W", "1", "2", "3"]

mdf = mrio.events
mdf[~mdf["state"].isin(VALID_EVENT_STAGES)].groupby(["subject", "run"])["TR"].count()

subject  run
07       1       30
         2      142
11       1       72
         3       42
         5      143
         6       57
17       6       14
20       5       28
23       2      427
         3       14
         6       41
27       5       28
28       6       71
Name: TR, dtype: int64

In [124]:
df = _df.copy()
df_inc = df[~df["excluded"]]
# df_inc.groupby(["subject", "run"])["excluded"]
mean_runs = df_inc.groupby("subject")["run"].count().mean()
subjects = len(df_inc["subject"].unique())

print("N subjects:", subjects)
print("Mean runs:", mean_runs)
print("Total runs", df_inc["run"].count())

N subjects: 31
Mean runs: 5.387096774193548
Total runs 167

In [131]:
167 - 138

29

In [130]:
df[df["subject"] == 16]

,subject,run,stage,excluded,eog_run_len,desc_add,invalid_stages,above_fd
0,16,1,eeg,True,0.0,clean-with-fd-clamped,False,False
1,16,2,eeg,True,282.0,clean-with-fd-clamped,False,False
2,16,3,eeg,True,0.0,clean-with-fd-clamped,False,False
3,16,4,eeg,True,234.0,clean-with-fd-clamped,False,False
4,16,5,eeg,True,0.0,clean-with-fd-clamped,False,False
61,16,1,global,False,NaN,clean-with-fd-clamped,False,False
62,16,2,global,False,NaN,clean-with-fd-clamped,False,False
63,16,3,global,False,NaN,clean-with-fd-clamped,False,False
64,16,4,global,False,NaN,clean-with-fd-clamped,False,False
65,16,5,global,False,NaN,clean-with-fd-clamped,False,False
66,16,6,global,False,NaN,clean-with-fd-clamped,False,False
70,16,7,global,False,NaN,clean-with-fd-clamped,False,False
72,16,8,global,False,NaN,clean-with-fd-clamped,False,False

In [129]:

_df_orig[_df_orig["subject"] == 16]

     subject  run   stage excluded invalid_stages above_fd desc_add
56        16    1  global    False          False    False    clean
59        16    2  global    False          False    False    clean
62        16    3  global    False          False    False    clean
65        16    4  global    False          False    False    clean
67        16    5  global    False          False    False    clean
71        16    6  global    False          False    False    clean
99        16    7  global    False          False    False    clean
104       16    8  global    False          False    False    clean

In [84]:
# df = df.copy()
# df_inc.groupby("subject")["run"].count().sum()
cer_excl = (df[df["coverage"] < 0.9])

for subj, sdf in cer_excl.groupby("subject"):
    orig_sdf = _df_orig[_df_orig["subject"] == subj]
    if len(sdf["run"].unique()) == len(orig_sdf["run"].unique()):
        print("whole subj excl", subj)
    print(f"runs_excl excl from {subj}", len(sdf["run"].unique()))
# (df[~df["eog_run_len"].isna()])

whole subj excl 3
runs_excl excl from 3 8
runs_excl excl from 8 1
runs_excl excl from 9 5
whole subj excl 12
runs_excl excl from 12 3
runs_excl excl from 14 3
runs_excl excl from 17 1
runs_excl excl from 31 1
runs_excl excl from 32 7

In [83]:
138 / 29

4.758620689655173